### ISSUE TITLE
Error message about .zip file

### ISSUE THREAD

**Issue by SaraJo** [noopkat/jewelbots-autodev#1]
Hi! This is great and I'm excited. Upon testing locally I got the following error message when doing the upload:

Error: Invalid value for "-pkg" / "--package": Path "/Users/sara/Development/Jewelbots/arduino-library/test.ino.zip" does not exist.

I thought maybe I'd test zipping up the sketch, but that resulted in a different error. 

Thank you!

**Comment by noopkat** [comment]
oh, weird! Sorry about that. Would you mind replying with the contents of the JSON config .jbauto you set up and where it was set up? Thanks for testing!!

**Comment by SaraJo** [comment]
Yup, was going to take a deeper dive but time got away from me. It is below:

`{
  "jewelbots-lib": "/Users/sara/Library/Arduino15/packages/Jewelbots_Arduino_Library",
  "arduino-app": "/Applications/Arduino.app",
  "build-destination": "/Users/sara/Development/Jewelbots/arduino-library",
  "sketch-file": "/Users/sara/Development/Jewelbots/sketches/test.ino"
}`

**Comment by noopkat** [comment]
hmm that seems to look ok!

when you look in the `/Users/sara/Development/Jewelbots/arduino-library` directory, do you see any files like the following? This is what I see in the build dir I specified on my machine after running the `compile` command:

```
blue.ino.bin  blue.ino.hex  blue.ino.zip        core            libraries  sketch
blue.ino.elf  blue.ino.map  build.options.json  includes.cache  preproc
```

**Comment by SaraJo** [comment]
I don't see those files. The compile command seems to be running well, however. Is there anything I need to have in the folder where I am running the command?

**Comment by noopkat** [comment]
I think I've only been running this in a dir with the json config, and the sketch file next to it or in a nested directory. The idea was that the json file sat in the same location as your sketch as it's tied to the project you're working on via the sketch contextually. However it should still work even if the sketch is in some other location from the json file.

This could be a weird path issue, I'm not fantastic at resolving paths effectively in Node 😛 

I'll try setting up a similar config file to you and see what happens on my end 😄

**Comment by glennblock** [comment]
I got the same error. `compile` worked, somewhat, but I don't notice any zip files in my build folder.

**Comment by noopkat** [comment]
I think tonight's bug fixes and @glennblock's great PR today should help resolve this issue, let me know 😁

**Comment by SaraJo** [comment]
You're the best! I'll confirm tomorrow.

**Comment by glennblock** [comment]
💪

**Comment by glennblock** [comment]
Teamwork!
