### ISSUE TITLE
uploading to Jewelbot is not currently supported on Linux

### ISSUE THREAD

**Issue by jmarca** [noopkat/jewelbots-autodev#7]
To quote the error message:

```
james@emma jewelbots_sketches$ jewelbots-autodev upload
found jewelbot on port /dev/ttyUSB0
Error: sorry, uploading to Jewelbot is not currently supported on Linux
    at /usr/local/lib/node_modules/jewelbots-autodev/lib/uploader.js:39:25
    at FSReqWrap.cb [as oncomplete] (fs.js:239:19)
```

I'll take a stab at it on my machine.

**Comment by noopkat** [comment]
oof. Is Linux now officially supported by Jewelbots? That was the reason for my error message in there. If they have published a flashing tool for Linux I'll be sure to update this and allow it. I'll dig into their docs and github repos this week if I get some time 😄

**Comment by jmarca** [comment]
Well, their help page certainly talks about linux, and if it didn't, I'd do my best make it happen because I don't run anything else!

**Comment by noopkat** [comment]
Great! Thanks for letting me know. At the time of writing this tool, there was no Linux support on the Jewelbots side of things. Let me see if I can release a new version of this on the weekend 😄

**Comment by noopkat** [comment]
Hi @jmarca I just published support for uploading to Jewelbots while using Linux. Let me know if this solves your issue 😁  Closing for now.

**Comment by jmarca** [comment]
Thanks, I'll try it tonight.
